import = ["~/sesh.local.toml"]

[[session]]
name = "Downloads 📥"
path = "~/Downloads"
startup_command="yazi"

[[session]]
name = "_dotfiles"
path = "~/.dotfiles"
startup_command = "tmuxifier w repo"

[[session]]
name = "main"
path = "~"

[[session]]
name = "nvim"
path = "~/.dotfiles/.config/nvim"
startup_command = "tmuxifier w repo"

[[session]]
name = "notes"
path = "~/Documents/notes"
startup_command = "nvim ."

[[session]]
name = "_ssh"
path = "~/.ssh"
startup_command = "nvim ."

[[session]]
name = "_costlinker"
startup_command = 'tmux set-option default-command "ssh costlinker" && ssh costlinker'

[[session]]
name = "etc"
path = "/etc"

[[session]]
name = "_home"
startup_command = 'tmux set-option default-command "ssh server" && hvpn && ssh server '
