import = ["~/sesh.local.toml"]

[[session]]
name = "Downloads 📥"
path = "~/Downloads"
startup_command="yazi"

[[session]]
name = "_dotfiles"
path = "~/.dotfiles"
startup_command = "tmuxifier w repo"

[[session]]
name = "main"
path = "~"

[[session]]
name = "nvim"
path = "~/.dotfiles/.config/nvim"
startup_command = "tmuxifier w repo"
