[mgr]
linemode = "mtime"
show_symlink = true
show_hidden = false

[opener]

edit = [
	{ run = 'nvim "$@"', block = true, for = "unix" },
]
play = [
	{ run = 'mpv "$@"', orphan = false, for = "unix" },
]
open = [
	{ run = 'xdg-open "$@"', desc = "xdg" },
]
browser = [
    { run = 'librewolf "$@"', orphan = true, for = "unix" },
]
image-edit = [
    { run = 'gimp "$@"', orphan = true, for = "unix" },
]
pdf-edit = [
    { run = 'pdfarranger "$@"', orphan = true, for = "unix" },
]
xournal = [
    { run = 'xournalpp "$@"', orphan = true, for = "unix" },
]
sqlite = [
    { run ='sqlitebrowser "$@"', orphan = false, for = "unix"}
]



[open]
prepend_rules = [
	{ mime = "image/*", use = [ "browser", "image-edit" ] },
	{ mime = "application/pdf", use = [ "browser", "pdf-edit", "xournal" ] },
	{ name = "*.db", use = [ "sqlite" ] },
    # { mime = "application/vnd.sqlite3", use = [ "sqlite" ] },
]   

# { name = "*.sqlite", ".sqlite3", ".db", ".db3", ".sdb", ".sl3", ".sqlite2", ".sqlite3", ".db2", ".s2db", ".sl2", use = [ "sqlite" ] },
