[manager]
linemode = "mtime"
show_symlink = true
show_hidden = false

[opener]

edit = [
	{ run = 'nvim "$@"', block = true, for = "unix" },
]
play = [
	{ run = 'mpv "$@"', orphan = true, for = "unix" },
]
open = [
	{ run = 'xdg-open "$@"', desc = "xdg" },
]
browser = [
    { run = 'librewolf "$@"', orphan = true, for = "unix" },
]
image-edit = [
    { run = 'gimp "$@"', orphan = true, for = "unix" },
]
pdf-edit = [
    { run = 'pdfarranger "$@"', orphan = true, for = "unix" },
]


[open]
prepend_rules = [
	{ mime = "image/*", use = [ "browser", "image-edit" ] },
	{ mime = "application/pdf", use = [ "browser", "pdf-edit" ] },
]   
