[manager]
linemode = "mtime"
show_symlink = true
show_hidden = false

[opener]

edit = [
	{ run = 'nvim "$@"', block = true, for = "unix" },
]
play = [
	{ run = 'mpv "$@"', orphan = true, for = "unix" },
]
open = [
	{ run = 'xdg-open "$@"', desc = "Open" },
]
