
- name: "Install all hyprland things I use"
  collections:
    - community.general

  hosts: localhost
  connection: local 

  tasks:
    - name: Upgrade pacman repos
      pacman:
        update_cache: true
      become: true

    - name: Install packages from official repos
      become: true
      pacman:
          name:  
            - hyprland
            - wofi
