
- name: "Install all hyprland things I use"
  collections:
    - community.general

  hosts: localhost
  connection: local 

  tasks:
    - name: Upgrade pacman repos
      pacman:
        update_cache: true
      become: true

    - name: Ensure directory exists
      ansible.builtin.file:
        path: ~/Pictures/scr

    - name: Ensure directory exists
      ansible.builtin.file:
        path: ~/Pictures/wallpapers

    - name: Install packages from official repos
      become: true
      pacman:
          name:  
            - hyprland
            - wofi
            - swaybg
            - wl-clipboard
            - wlsunset
            - cliphist
            - grim
            - swappy
            - slurp
            - converseen
            - procps-ng
            - mako
            - brightnessctl
            - acpi # battery power
            - nm-connection-editor
            - pavucontrol
            - xdg-desktop-portal-hyprland

            # ashell bar and dependencies
    
             
    - name: install programs from aur
      kewlfft.aur.aur:
        use: yay
        name:
          - ashell
          - python-pywal16


