- import_playbook: install-yay.yaml

- name: Install ansible modules to manage aur packages
  hosts: localhost
  connection: local 

  tasks:
    - name: Install modules from requirements.yaml
      community.general.ansible_galaxy_install:
        type: both
        requirements_file: requirements.yaml

- name: "Install all programs I use"
  collections:
    - community.general
    - kewlfft.aur

  hosts: localhost
  connection: local 

  tasks:
    - name: Upgrade pacman repos
      pacman:
        update_cache: true
      become: true

    - name: Install packages from official repos
      become: true
      pacman:
          name: 
            - zoxide
            - neovim
            - tmux
            - fd
            - bat
            - htop
            - timeshift
            - stow
            - git
            - base-devel
            - fzf
            - ripgrep
            - lazygit
            - fastfetch
            - lsd
            - kitty
            - yazi
            - ncdu
            - unp
            - curl
            - zsh-syntax-highlighting
            - zsh-autosuggestions 


            - chromium
            - mpv
          state: present

    - name: Install fonts from official repos
      become: true
      pacman:
        name:
          - ttf-font-awesome
          - ttf-jetbrains-mono
          - ttf-jetbrains-mono-nerd
          - ttf-fira-code 
          - noto-fonts 
          - noto-fonts-cjk 
          - noto-fonts-emoji 
          - noto-fonts-extra
          - adobe-source-sans-fonts
          - powerline-fonts 
          - awesome-terminal-fonts
        state: present

    - name: Install programs from aur
      kewlfft.aur.aur:
        use: yay
        name:
          - otf-apple-fonts
          - librewolf-bin
          - downgrade
          - rate-mirrors-bin

    - name: Creates repos directory
      ansible.builtin.file:
        path: $HOME/repos
        state: directory

    - name: install sesh
      shell: go install github.com/joshmedeski/sesh@latest

